Vagrant.configure("2") do |config|
  config.vm.box = "./lrs.box"
  config.vm.network 'forwarded_port', guest: 3000, host: 3000, auto_correct: true
  config.vm.network 'forwarded_port', guest: 3306, host: 8306, auto_correct: true
end
